name: SAST Workflow

on:
  workflow_call:

jobs:
  sast:
    name: CodeQL SAST Scan
    uses: wjmurphy/pipeline_security/.github/workflows/codeql.yml@main
    with:
      config-path: sast_configurations/.github/sast_configurations/codeql.yml
    # permissions:
    #   actions: read
    #   contents: read
    #   security-events: write
